// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIOLJTnMJe-5UoUPNIAsZlvIAbykx7qig',
    appId: '1:81791802787:web:f45b65c942f33e5c6d0e16',
    messagingSenderId: '81791802787',
    projectId: 'qr-code-scanner-dev-b0cfa',
    authDomain: 'qr-code-scanner-dev-b0cfa.firebaseapp.com',
    storageBucket: 'qr-code-scanner-dev-b0cfa.appspot.com',
    measurementId: 'G-LRBWQG85KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEDCKrhDYdK3nURzcDMbIuvr1CDRUVRM0',
    appId: '1:81791802787:android:15d712f44e5901a56d0e16',
    messagingSenderId: '81791802787',
    projectId: 'qr-code-scanner-dev-b0cfa',
    storageBucket: 'qr-code-scanner-dev-b0cfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKscE6I_d2FF1IoALoDjeAQu_uXY9o48Y',
    appId: '1:81791802787:ios:8f93addc372ad8976d0e16',
    messagingSenderId: '81791802787',
    projectId: 'qr-code-scanner-dev-b0cfa',
    storageBucket: 'qr-code-scanner-dev-b0cfa.appspot.com',
    iosBundleId: 'com.cnt.scanQrCode.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKscE6I_d2FF1IoALoDjeAQu_uXY9o48Y',
    appId: '1:81791802787:ios:8f93addc372ad8976d0e16',
    messagingSenderId: '81791802787',
    projectId: 'qr-code-scanner-dev-b0cfa',
    storageBucket: 'qr-code-scanner-dev-b0cfa.appspot.com',
    iosBundleId: 'com.cnt.scanQrCode.dev',
  );
}
