// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYic7HH7rfznVrMJrAvqNYVDiwqc6atFQ',
    appId: '1:230866415418:web:00cd5b99ec4ed46b3a6a03',
    messagingSenderId: '230866415418',
    projectId: 'qr-code-scanner-dev',
    authDomain: 'qr-code-scanner-dev.firebaseapp.com',
    storageBucket: 'qr-code-scanner-dev.appspot.com',
    measurementId: 'G-X5NNPSW9Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQdtnvUANyZZL-utaYZnnoKu19vTARo6c',
    appId: '1:230866415418:android:ba972ed8e8709a8f3a6a03',
    messagingSenderId: '230866415418',
    projectId: 'qr-code-scanner-dev',
    storageBucket: 'qr-code-scanner-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq2WLlxZlmP0X-EUwp26bMCCve2dlduCU',
    appId: '1:230866415418:ios:57fe902250c43a373a6a03',
    messagingSenderId: '230866415418',
    projectId: 'qr-code-scanner-dev',
    storageBucket: 'qr-code-scanner-dev.appspot.com',
    iosBundleId: 'com.example.scanQrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq2WLlxZlmP0X-EUwp26bMCCve2dlduCU',
    appId: '1:230866415418:ios:10d9770ba25f9eae3a6a03',
    messagingSenderId: '230866415418',
    projectId: 'qr-code-scanner-dev',
    storageBucket: 'qr-code-scanner-dev.appspot.com',
    iosBundleId: 'com.example.scanQrCode.RunnerTests',
  );
}
