// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc-wDwrfyCIU94C9OsVpKt9TvkypZY1wM',
    appId: '1:441789829721:web:8dd288517ad5df2df09748',
    messagingSenderId: '441789829721',
    projectId: 'qr-code-scanner-prod',
    authDomain: 'qr-code-scanner-prod.firebaseapp.com',
    storageBucket: 'qr-code-scanner-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrBYtRqf6oa0YpkqgEWtZdFQNyn3xKU3w',
    appId: '1:441789829721:android:660ad63872596282f09748',
    messagingSenderId: '441789829721',
    projectId: 'qr-code-scanner-prod',
    storageBucket: 'qr-code-scanner-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGMj6kfa2oUtUjonlz7t3sTDuUpoY1lfc',
    appId: '1:441789829721:ios:7e0c469d3ef58aa7f09748',
    messagingSenderId: '441789829721',
    projectId: 'qr-code-scanner-prod',
    storageBucket: 'qr-code-scanner-prod.appspot.com',
    iosBundleId: 'com.cnt.scanQrCode.prod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGMj6kfa2oUtUjonlz7t3sTDuUpoY1lfc',
    appId: '1:441789829721:ios:7e0c469d3ef58aa7f09748',
    messagingSenderId: '441789829721',
    projectId: 'qr-code-scanner-prod',
    storageBucket: 'qr-code-scanner-prod.appspot.com',
    iosBundleId: 'com.cnt.scanQrCode.prod',
  );
}
