// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3y63WWPaqC3pMH2DDsnSl6AblFm5J7lY',
    appId: '1:996911916116:web:7df303357054726f3379c1',
    messagingSenderId: '996911916116',
    projectId: 'qr-code-scanner-4661e',
    authDomain: 'qr-code-scanner-4661e.firebaseapp.com',
    storageBucket: 'qr-code-scanner-4661e.appspot.com',
    measurementId: 'G-MKJXD5PG9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1zdTqTEBIF96YlhogYvUM4JYlhWMt_w',
    appId: '1:996911916116:android:726f7136acf8f3043379c1',
    messagingSenderId: '996911916116',
    projectId: 'qr-code-scanner-4661e',
    storageBucket: 'qr-code-scanner-4661e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDplAlANJtMIKvVKE21doULTFCOx84gDcA',
    appId: '1:996911916116:ios:910750a6ee6b7e943379c1',
    messagingSenderId: '996911916116',
    projectId: 'qr-code-scanner-4661e',
    storageBucket: 'qr-code-scanner-4661e.appspot.com',
    iosBundleId: 'com.example.scanQrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDplAlANJtMIKvVKE21doULTFCOx84gDcA',
    appId: '1:996911916116:ios:a1efb10abab38f2e3379c1',
    messagingSenderId: '996911916116',
    projectId: 'qr-code-scanner-4661e',
    storageBucket: 'qr-code-scanner-4661e.appspot.com',
    iosBundleId: 'com.example.scanQrCode.RunnerTests',
  );
}
