# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Prod Build to Crashlytics Beta"
  lane :betaprod do
    gradle(
      task: "clean"
    ) 
    sh("./build_android_prod.sh")
    # latest_release = firebase_app_distribution_get_latest_release(
    #   app: "1:996911916116:android:726f7136acf8f3043379c1",
    #   firebase_cli_token: "1//0eXWxmSvCFfaZCgYIARAAGA4SNwF-L9IrANWO7VgzUFyYd3oIhxLrdhFAJkhzApWZxbCK9MXEBsKsv3KelHxIHxkpOoUEB_G9RLA",
    # )
    # increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })
    release = firebase_app_distribution(
            app: "1:996911916116:android:23b3bd12d36a844b3379c1",
            groups: "QRCodeScanner-tester",
            release_notes: "Fixing bug in features",
            apk_path: "../build/app/outputs/flutter-apk/app-prod-release.apk",
            firebase_cli_token: "1//0eXWxmSvCFfaZCgYIARAAGA4SNwF-L9IrANWO7VgzUFyYd3oIhxLrdhFAJkhzApWZxbCK9MXEBsKsv3KelHxIHxkpOoUEB_G9RLA"
        )
  end

  desc "Submit a new Beta Dev Build to Crashlytics Beta"
  lane :betadev do
    gradle(
      task: "clean"
    ) 
    sh("./build_android_dev.sh")
    # latest_release = firebase_app_distribution_get_latest_release(
    #   app: "1:996911916116:android:726f7136acf8f3043379c1",
    #   firebase_cli_token: "1//0eXWxmSvCFfaZCgYIARAAGA4SNwF-L9IrANWO7VgzUFyYd3oIhxLrdhFAJkhzApWZxbCK9MXEBsKsv3KelHxIHxkpOoUEB_G9RLA",
    # )
    # increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })
    release = firebase_app_distribution(
            app: "1:230866415418:android:0fb3e831ca60849c3a6a03",
            groups: "QRCodeScanner-tester",
            release_notes: "Fixing bug in features",
            apk_path: "../build/app/outputs/flutter-apk/app-dev-release.apk",
            firebase_cli_token: "1//0eXWxmSvCFfaZCgYIARAAGA4SNwF-L9IrANWO7VgzUFyYd3oIhxLrdhFAJkhzApWZxbCK9MXEBsKsv3KelHxIHxkpOoUEB_G9RLA"
        )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
