name: build apk dev
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: macos-latest
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    - name: Bundle install
      run: cd ./android && bundle install
    steps:
      - run: bundle exec fastlane betadev