name: Build Beta APK

on:
  push:
    branches: [ develop ]

jobs:
  build-beta-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Install Fastlane
        run: |
          gem install fastlane

      - name: Build Beta APK
        working-directory: android
        run: |
          cd android && bundle exec fastlane betadev