name: build apk dev
on:
  push:
    branches:
      - develop
jobs:
  run:
    runs-on: macos-latest
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    steps:
      - run: cd android
      - run: bundle exec fastlane betadev