name: Build Beta APK

on:
  push:
    branches: [develop]

jobs:
  build-beta-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: "3.1" # Not needed with a .ruby-version file

      - name: Install Bundler
        working-directory: android
        run: bundle install

      - name: Install Fastlane
        working-directory: android
        run: |
          gem install fastlane

      - name: Build Beta APK
        working-directory: android
        run: |
          bundle exec fastlane betadev
