name: build apk dev
on:
  push:
    branches:
      - develop
jobs:
  build-apk:
    runs-on: macos-latest
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    steps:
      - run: cd android && bundle exec fastlane betadev